const Types = {
  STEPS: {
    INITIAL: "INITIAL",
    CHOOSING_GAME: "CHOOSING_GAME",
    CHOOSING_PLAYERS: "CHOOSING_PLAYERS",
    CHOOSING_WINNER: "CHOOSING_WINNER",
    REVIEWING_SUBMISSION: "REVIEWING_SUBMISSION",
    SUBMITTED: "SUBMITTED",
  },
}

export default Types
