// const actionTypes = {
// 	this.STEP_INITIAL = "INITIAL"
// 	STEP_CHOOSING_GAME: "CHOOSING_GAME",
// 	STEP_CHOOSING_PLAYERS: "CHOOSING_PLAYERS",
// 	STEP_CHOOSING_WINNER: "CHOOSING_WINNER",
// 	STEP_REVIEWING_SUBMISSION: "REVIEWING_SUBMISSION",
// 	STEP_SUBMITTED: "SUBMITTED",

// 	SET_STEP: "SET_STEP",
// 	SET_GAME: "SET_GAME",
// 	SET_PLAYERS: "SET_PLAYERS",
// 	SET_WINNER: "SET_WINNER",
// }

function Types() {
	this.STEP_INITIAL = "INITIAL"
	this.STEP_CHOOSING_GAME = "CHOOSING_GAME"
	this.STEP_CHOOSING_PLAYERS = "CHOOSING_PLAYERS"
	this.STEP_CHOOSING_WINNER = "CHOOSING_WINNER"
	this.STEP_REVIEWING_SUBMISSION = "REVIEWING_SUBMISSION"
	this.STEP_SUBMITTED = "SUBMITTED"

	this.SET_STEP = "SET_STEP"
	this.SET_GAME = "SET_GAME"
	this.SET_PLAYERS = "SET_PLAYERS"
	this.SET_WINNER = "SET_WINNER"

	this.STEPS_ORDERED = [
		this.STEP_CHOOSING_GAME,
		this.STEP_CHOOSING_PLAYERS,
		this.STEP_CHOOSING_WINNER,
		this.STEP_REVIEWING_SUBMISSION,
	]
}

const T = new Types()

export default T
